using DG.Tweening; // Make sure you have the DoTween namespace

public enum EaseTypes
{
    Unset = Ease.Unset,
    Linear = Ease.Linear,
    InSine = Ease.InSine,
    OutSine = Ease.OutSine,
    InOutSine = Ease.InOutSine,
    InQuad = Ease.InQuad,
    OutQuad = Ease.OutQuad,
    InOutQuad = Ease.InOutQuad,
    InCubic = Ease.InCubic,
    OutCubic = Ease.OutCubic,
    InOutCubic = Ease.InOutCubic,
    InQuart = Ease.InQuart,
    OutQuart = Ease.OutQuart,
    InOutQuart = Ease.InOutQuart,
    InQuint = Ease.InQuint,
    OutQuint = Ease.OutQuint,
    InOutQuint = Ease.InOutQuint,
    InExpo = Ease.InExpo,
    OutExpo = Ease.OutExpo,
    InOutExpo = Ease.InOutExpo,
    InCirc = Ease.InCirc,
    OutCirc = Ease.OutCirc,
    InOutCirc = Ease.InOutCirc,
    InElastic = Ease.InElastic,
    OutElastic = Ease.OutElastic,
    InOutElastic = Ease.InOutElastic,
    InBack = Ease.InBack,
    OutBack = Ease.OutBack,
    InOutBack = Ease.InOutBack,
    InBounce = Ease.InBounce,
    OutBounce = Ease.OutBounce,
    InOutBounce = Ease.InOutBounce,
    Flash = Ease.Flash,
    InFlash = Ease.InFlash,
    OutFlash = Ease.OutFlash,
    InOutFlash = Ease.InOutFlash
}